variables:
  MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode"    
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
  GIT_STRATEGY: clone

cache:
  paths:
    - .m2/repository
    
before_script:
    - 'wget -P .m2/ --no-check-certificate $MPDFT_MVN_SETTINGS'
  
stages:
  - tests
  - publish  
  
Automated Testing:
  stage: tests
  image: maven:3.3.9-jdk-8
  script:
    - 'mvn $MAVEN_CLI_OPTS verify $MAVEN_OPTS -Dmaven.test.skip=false'
    - 'cat target/site/jacoco/index.html || true'
  except:
    - tags
  tags: 
    - docker  
  
Quality Analysis:
  stage: tests
  image: maven:3.3.9-jdk-8
  script:
    - 'mvn $MAVEN_CLI_OPTS verify sonar:sonar $MAVEN_OPTS -Dsonar.host.url=$MPDFT_SONAR_URL -Dmaven.test.skip=false'
  only:
    - master    
  tags: 
    - docker
    
Release e Nexus:  
  stage: publish
  image: maven:3.3.9-jdk-8
  before_script:
    - 'wget -P .m2/ --no-check-certificate $MPDFT_MVN_SETTINGS'
    - eval $(ssh-agent -s)
    - echo "$MPDFT_CI_USER_SSH_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - mkdir -p ~/.ssh && chmod 700 ~/.ssh
    - echo "$MPDFT_SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - export PROJECT_VERSION=$(grep --max-count=1 '<version>' pom.xml | awk -F '>' '{ print $2 }' | awk -F '<' '{ print $1 }')
    - DISI_CI_BRANCH=$CI_PROJECT_NAME-$PROJECT_VERSION
    - DISI_MAIN_BRANCH=master
    - git config --global user.email $MPDFT_CI_EMAIL
    - git config --global user.name  $MPDFT_CI_USER
    - git config --global push.default simple
    - 'curl -s --request DELETE --header "PRIVATE-TOKEN: $MPDFT_CI_USER_TOKEN" "$MPDFT_GITLAB/api/v4/projects/$CI_PROJECT_ID/protected_branches/master" '
  script:
    - git remote set-url origin ssh://git@$MPDFT_GITLAB_SSH/$CI_PROJECT_PATH.git
    - git checkout -b $DISI_CI_BRANCH $DISI_MAIN_BRANCH
    - mvn $MAVEN_CLI_OPTS jgitflow:release-start  $MAVEN_CLI_OPTS -Pproducao -DCI_DEVELOP_BRANCH=$DISI_MAIN_BRANCH -DCI_MASTER_BRANCH=$DISI_CI_BRANCH -DCI_USER=$MPDFT_CI_USER -DCI_PASSWORD=$MPDFT_CI_PASSWORD
    - mvn $MAVEN_CLI_OPTS jgitflow:release-finish $MAVEN_CLI_OPTS -Pproducao -DRELEASE_REPOSITORY_URL=$MPDFT_NEXUS_RELEASE_URL -DCI_DEVELOP_BRANCH=$DISI_MAIN_BRANCH -DCI_MASTER_BRANCH=$DISI_CI_BRANCH -DCI_USER=$MPDFT_CI_USER -DCI_PASSWORD=$MPDFT_CI_PASSWORD
    - git push origin
    - git push origin --tags --quiet
  after_script:
    - 'curl -s --request POST --header "PRIVATE-TOKEN: $MPDFT_CI_USER_TOKEN" "$MPDFT_GITLAB/api/v4/projects/$CI_PROJECT_ID/protected_branches?name=master&push_access_level=0&merge_access_level=40"'
  when: manual
  only:
    - master
  tags: 
    - docker 